insert into proyectos_curriculares values (1, 'Ingeniería de Producción');
insert into proyectos_curriculares values (2, 'Ingeniería Eléctrica');
insert into proyectos_curriculares values (3, 'Ingeniería en Control y Automatización');
insert into proyectos_curriculares values (4, 'Ingeniería en Telecomunicaciones');
insert into proyectos_curriculares values (5, 'Ingeniería en Telemática');
insert into proyectos_curriculares values (6, 'Ingeniería Mecánica');
insert into proyectos_curriculares values (7, 'Tecnología en Construcciones Civiles');
insert into proyectos_curriculares values (8, 'Tecnología en Electricidad de Media y Baja Tensión');
insert into proyectos_curriculares values (9, 'Tecnología en Electrónica Industrial');
insert into proyectos_curriculares values (10, 'Tecnología en Gestión de la Producción Industrial');
insert into proyectos_curriculares values (11, 'Tecnología en Mecánica Industrial');
insert into proyectos_curriculares values (12, 'Tecnología en Sistematización de Datos');